ci: update gitleaks version & allow trivy fs scan even if image scan didnt work

diff --git a/.github/workflows/trivy.yml b/.github/workflows/trivy.yml
--- a/.github/workflows/trivy.yml
+++ b/.github/workflows/trivy.yml
@@ -21,6 +21,8 @@ jobs:
         run: docker build -t gistsapp/api:${{ github.sha }} .
 
       - name: Run Trivy image scan
+        id: trivy_image
+        continue-on-error: true
         uses: aquasecurity/trivy-action@0.31.0
         with:
           image-ref: 'gistsapp/api:${{ github.sha }}'
@@ -31,6 +33,8 @@ jobs:
           severity: 'CRITICAL,HIGH'
 
       - name: Run Trivy filesystem scan
+        id: trivy_fs
+        continue-on-error: true
         uses: aquasecurity/trivy-action@0.31.0
         with:
           scan-type: 'fs'
@@ -39,3 +43,12 @@ jobs:
           exit-code: '1'
           ignore-unfixed: true
           severity: 'CRITICAL,HIGH'
+
+      - name: Fail job if any Trivy scan failed
+        run: |
+          if [ "${{ steps.trivy_image.outcome }}" != "success" ] || [ "${{ steps.trivy_fs.outcome }}" != "success" ]; then
+            echo "❌ One or both Trivy scans failed."
+            exit 1
+          else
+            echo "✅ Both Trivy scans passed."
+          fi
